# site settings
title: Mike Harrison
subtitle: creative
email: mike@mikejharrison.com
description: A creative language teaching professional
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: #
city: London
state: #
zip_code: #
country: United Kingdom
phone: #

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: #
googleplus_url: #
instagram_url: #
linkedin_url: #
pinterest_url: #
slack_url: #
twitter_url: https://twitter.com/harrisonmike

# build settings
markdown: kramdown

sass:
  style: compressed
